before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
- env:
  - CGO_ENABLED=0
  main: ./cmd/system-deploy
  goos:
  - linux
archives:
- replacements:
    darwin: darwin
    linux: linux
    windows: windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
signs:
  - artifacts: checksum
